apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: employees
  description: The employees API
  tags:
    - employees
    - query
    - rest
  links:
    - url: https://github.com/gsoeldner-sc/backstage-sample-app
      title: Server Root
      icon: github
spec:
  type: cors-openapi
  lifecycle: experimental
  owner: guests
  definition:
    $text: http://localhost:8080/v3/api-docs